{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 > 1", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个很厉害的测试用例\")\n    def test_3():\n>       assert 0>1\nE       assert 0 > 1\n\ntest_3.py:18: AssertionError"}, "start": 1566180923429, "stop": 1566180923429, "uuid": "2e4e26ac-2eb3-44a3-a7ff-a860fd82f5a7", "historyId": "c30e049cfce40e7d96439ad218fba7a6", "fullName": "test_3#test_3", "labels": [{"name": "story", "value": "这是一个很厉害的测试用例"}, {"name": "feature", "value": "模块二"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_3"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-1ECG2I3"}, {"name": "thread", "value": "9220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_3"}]}